<?php
$metaTags = <<<HTML
<!-- Primary Meta Tags -->
<title>Privacy and Policy</title>
<meta name="title" content="Privacy">
<meta name="description" content="Privacy and policy predictions with informed analysis for better decision-making in your football bets.">
<meta name="keywords" content="btts, ng, gg, picks, ">

<!-- Open Graph -->
<meta property="og:title" content="AccurateStakes - Accurate Prediction Site ">
<meta property="og:description" content="AccurateStakes provides free football predictions daily from experienced tipsters.">

<!-- Twitter -->
<meta property="twitter:title" content="AccurateStakes - Accurate Prediction Site ">
<meta property="twitter:description" content="AccurateStakes provides free football predictions daily from experienced tipsters.">
HTML;

// Preloader & Header
include_once BASE_PATH . "/components/includes/header.inc.php";
include_once BASE_PATH . "/components/shared/preloader.shared.php";
include_once BASE_PATH . "/components/includes/navbar.inc.php";
?>

<br/>
<main class="desktop-container" style="width: 100%; background-color: white; border: 1px solid #ddd">
<div class="container p-4 pt-2">
    <div class="row">
        <div class="col-12 flex-container p-0">
            <h1 style="font-weight:bold;font-size:xx-large"><strong>Privacy Policy</strong></h1>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-12 p-0" style="font-size: medium;">
            <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Accurate Stakes service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>Words with capitalized first letters have defined meanings as described in the definitions below. These definitions shall apply whether they appear in singular or plural form.</p>

            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other voting securities.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to Accurate Stakes.</li>
                <li><strong>Cookies</strong> are small files placed on Your device by a website, often used for storing browsing preferences and activity.</li>
                <li><strong>Country</strong> refers to: Kenya</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, mobile phone, or tablet.</li>
                <li><strong>Personal Data</strong> is any information relating to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Website.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. This includes third-party vendors or individuals assisting with the Service.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Website</strong> refers to Accurate Stakes, accessible from <a href="https://www.amazingstakes.com/" target="_blank" rel="noopener noreferrer">https://www.amazingstakes.com/</a></li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or legal entity on behalf of which such individual is accessing or using the Service.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>

            <h4>Personal Data</h4>
            <p>We may ask You to provide certain personally identifiable information such as:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically and may include Your IP address, browser type and version, pages visited, time and date of visit, and other diagnostic data.</p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies such as web beacons and scripts to monitor and analyze Service usage and improve user experience.</p>

            <ul>
                <li><strong>Cookies or Browser Cookies:</strong> Small files stored on your Device. You can configure your browser to reject all Cookies or alert you when a Cookie is sent. However, disabling Cookies may affect functionality.</li>
                <li><strong>Web Beacons:</strong> Electronic files used to count users and gather analytics (e.g., email opens, webpage views).</li>
            </ul>

            <p>Types of Cookies we use:</p>
            <ul>
                <li>
                    <strong>Necessary Cookies</strong> – Required for essential features and security. (Session Cookies)
                </li>
                <li>
                    <strong>Consent Cookies</strong> – Store your cookie preferences. (Persistent Cookies)
                </li>
                <li>
                    <strong>Functionality Cookies</strong> – Remember login, preferences, and settings. (Persistent Cookies)
                </li>
            </ul>

            <h3>Use of Your Personal Data</h3>
            <ul>
                <li><strong>To provide and maintain our Service</strong></li>
                <li><strong>To manage Your Account</strong></li>
                <li><strong>To perform a contract</strong></li>
                <li><strong>To contact You</strong> via email, phone, or messaging platforms</li>
                <li><strong>To provide news, offers, or general information</strong> unless You opt out</li>
                <li><strong>To manage requests</strong> from You</li>
                <li><strong>To analyze data</strong> and improve user experience</li>
            </ul>

            <h3>Sharing Your Personal Data</h3>
            <p>We may share Your information in the following situations:</p>
            <ul>
                <li>With Service Providers to analyze usage and support our operations</li>
                <li>For business transfers or restructuring</li>
                <li>With Affiliates or trusted partners under confidentiality agreements</li>
                <li>To comply with legal obligations or protect rights</li>
            </ul>

            <h3>Retention of Your Personal Data</h3>
            <p>We retain Your Personal Data only as long as necessary for the purposes outlined in this Privacy Policy and to comply with legal obligations.</p>

            <h3>Transfer of Your Personal Data</h3>
            <p>Your information may be transferred to — and maintained on — computers outside Your country where data protection laws may differ. Your consent to this Privacy Policy represents agreement to that transfer.</p>

            <h3>Security of Your Personal Data</h3>
            <p>We strive to use commercially acceptable means to protect Your Personal Data, but no method of transmission or storage is 100% secure.</p>

            <h3>Children's Privacy</h3>
            <p>Our Service does not knowingly collect information from individuals under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

            <h3>Links to Other Websites</h3>
            <p>Our Service may contain links to third-party sites. We are not responsible for the content or privacy practices of any third-party sites.</p>

            <h2>Your Rights</h2>
            <p>You have the right to:</p>
            <ul>
                <li>Access and update Your information</li>
                <li>Request deletion of Your Personal Data</li>
                <li>Withdraw consent at any time</li>
                <li>Object to processing or request data portability</li>
            </ul>

            <h2>Changes to This Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. Changes will be posted on this page with an updated “Last updated” date. You are advised to review this page periodically.</p>

        </div>
    </div>
</div>
</main>

<?php
// Footer
include_once BASE_PATH . "/components/includes/footer.inc.php";
?>
